import React from "react";

const TermsOfService = () => {
  return (
    <div className="min-h-screen flex justify-center items-start bg-gray-50 py-12 px-6">
       {/* Main Content */}
        <main className="flex flex-col  max-w-4xl border border-gray-300 rounded-lg mx-auto px-6  py-10">
          {/* Page Title */}
          <div className="text-center mb-10">
            <h1 className="text-3xl md:text-4xl font-bold text-eduBlue">
              Terms Of Service  – EduPrint
            </h1>
            <p className="text-gray-600 mt-3 text-sm md:text-base max-w-3xl mx-auto">
              This document is an electronic record in terms of the Information
              Technology Act, 2000 and rules thereunder. By using our platform,
              you agree to comply with these Terms.
            </p>
          </div>

          {/* Terms Sections */}
          <section className="bg-white shadow-sm rounded-xl p-6 border border-gray-100 space-y-8">
            {/* Introduction */}
            <article>
              <div className="flex justify-between">
                <h2 className="text-xl font-semibold text-eduBlue mb-3">
                  Introduction
                </h2>
                <h3 className="text-black text-sm">
                  Last Updated: 31-Oct-2025
                </h3>
              </div>
              <p className="text-gray-700 leading-relaxed text-sm md:text-base">
                This document is an electronic record in terms of the
                Information Technology Act, 2000 and rules thereunder as
                applicable, and the amended provisions pertaining to electronic
                records in various statutes as amended by the Information
                Technology Act, 2000. This electronic record is generated by a
                computer system and does not require any physical or digital
                signatures.
              </p>
              <p className="text-gray-700 leading-relaxed text-sm md:text-base mt-4">
                This document is published in accordance with Rule 3 (1) of the
                Information Technology (Intermediaries Guidelines) Rules, 2011,
                which requires publishing the rules and regulations, privacy
                policy, and Terms of Use for access or usage of domain name
                <span className="font-medium">
                  {" "}
                  eduskill.educerns.org{" "}
                </span>{" "}
                (hereinafter referred to as the "Website"), including the
                related mobile application (hereinafter referred to as the
                "Platform").
              </p>
              <p className="text-gray-700 leading-relaxed text-sm md:text-base mt-4">
                The Platform is owned and operated by Educerns Technologies
                Private Limited, a company incorporated under the Companies Act,
                1956 with its registered office in Maharashtra, India
                (hereinafter referred to as the "Company," "we," "us," or
                "our").
              </p>
              <p className="text-gray-700 leading-relaxed text-sm md:text-base mt-4">
                Your use of EduPrint, its Platform, and associated
                services are governed by the following Terms and Conditions
                ("Terms of Use"), which constitute a binding agreement between
                you and Educerns Technologies Private Limited. By using our
                Platform, you agree to comply with these Terms. If you do not
                agree, please refrain from accessing or using the Platform.
              </p>
            </article>

            {/* 1. Definitions */}
            <article>
              <h2 className="text-xl font-semibold text-eduBlue mb-3">
                1. Definitions
                <p>For the purpose of these Terms:</p>
              </h2>
              <ul className="pl-6 space-y-2 text-gray-700 text-sm md:text-base">
                <li>
                  <span className="font-medium">1.1</span>{" "}
                  <strong>User:</strong> "User" means any individual who
                  accesses or uses the Platform
                </li>
                <li>
                  <span className="font-medium">1.2</span>{" "}
                  <strong>Services:</strong> means all services provided through
                  the Platform including certifications, examinations, and
                  related features
                </li>
                <li>
                  <span className="font-medium">1.3</span>{" "}
                  <strong>Content:</strong> means all information, data, text,
                  software, music, sound, photographs, graphics, video,
                  messages, or other materials
                </li>
                <li>
                  <span className="font-medium">1.4</span>{" "}
                  <strong>Account:</strong> means the user account created on
                  the Platform
                </li>
              </ul>
            </article>

            <article>
              <h2 className="text-xl font-semibold text-eduBlue mb-3">
                2. Acceptance of Terms
              </h2>
              <ul className="pl-6 space-y-2 text-gray-700 text-sm md:text-base">
                <li>
                  <span className="font-medium">2.1</span> By accessing or using
                  EduPrint, you acknowledge that you have read,
                  understood, and agree to be bound by these Terms.
                </li>
                <li>
                  <span className="font-medium">2.2</span> We reserve the right
                  to modify these Terms at any time. Changes will be effective
                  immediately upon posting. Continued use of the Platform after
                  modifications constitutes acceptance of the updated Terms.
                </li>
                <li>
                  <span className="font-medium">2.3</span> If you disagree with
                  any modifications, you must discontinue use of the Platform.
                </li>
              </ul>
            </article>

            {/* 3. Eligibility & User Account */}
            <article>
              <h2 className="text-xl font-semibold text-eduBlue mb-3">
                3. Eligibility & User Account
              </h2>
              <ul className="pl-6 space-y-2 text-gray-700 text-sm md:text-base">
                <li>
                  <span className="font-medium">3.1</span> You must be at least
                  18 years of age or accessing under the supervision of a
                  parent/guardian to use EduPrint.
                </li>
                <li>
                  <span className="font-medium">3.2</span> You agree to provide
                  accurate, current, and complete information during
                  registration and maintain its accuracy thereafter.
                </li>
                <li>
                  <span className="font-medium">3.3</span> You are solely
                  responsible for all activities that occur under your account.
                  Safeguarding your login credentials is your responsibility.
                </li>
                <li>
                  <span className="font-medium">3.4</span> You must immediately
                  notify us of any unauthorized use of your account or any other
                  breach of security.
                </li>
                <li>
                  <span className="font-medium">3.5</span> One person may
                  maintain only one active account unless explicitly permitted
                  by us.
                </li>
              </ul>
            </article>

            {/* 4. Services */}
            <article>
              <h2 className="text-xl font-semibold text-eduBlue mb-3">
                4. Services
              </h2>
              <ul className="pl-6 space-y-2 text-gray-700 text-sm md:text-base">
                <li>
                  <span className="font-medium">4.1</span> EduPrint
                  provides certification and examination services for
                  skill-based learning programs.
                </li>
                <li>
                  <span className="font-medium">4.2</span> The Platform may also
                  facilitate:
                  <ul className="list-disc pl-6 mt-2 space-y-1">
                    <li>Online tests and evaluations</li>
                    <li>Digital certification issuance</li>
                    <li>Integration with EduCerns franchise partners</li>
                    <li>
                      Resume-building features for learners after course
                      completion
                    </li>
                    <li>Study materials and resources</li>
                    <li>Progress tracking and analytics</li>
                  </ul>
                </li>
                <li>
                  <span className="font-medium">4.3</span> The Company reserves
                  the right to modify, update, or discontinue any part of the
                  Services with reasonable notice to users.
                </li>
                <li>
                  <span className="font-medium">4.4</span> We do not guarantee
                  uninterrupted or error-free operation of the Platform.
                </li>
                <li>
                  <span className="font-medium">4.5</span> Technical
                  requirements for using the Platform are specified on our
                  website and may be updated from time to time.
                </li>
              </ul>
            </article>

            {/* 5. Use of Platform */}
            <article>
              <h2 className="text-xl font-semibold text-eduBlue mb-3">
                5. Use of Platform
              </h2>
              <ul className="pl-6 space-y-2 text-gray-700 text-sm md:text-base">
                <li>
                  <span className="font-medium">5.1</span> You agree to use
                  EduPrint only for lawful purposes and in accordance
                  with these Terms.
                </li>
                <li>
                  <span className="font-medium">5.2</span> You must not:
                  <ul className="list-disc pl-6 mt-2 space-y-1">
                    <li>Attempt to hack, disrupt, or misuse the Platform</li>
                    <li>
                      Use content, logos, or certificates without authorization
                    </li>
                    <li>
                      Engage in fraudulent exam practices or misuse
                      certification
                    </li>
                    <li>Create multiple accounts to circumvent restrictions</li>
                    <li>Share login credentials with third parties</li>
                    <li>
                      Use automated systems or bots to access the Platform
                    </li>
                    <li>Upload malicious code or content</li>
                    <li>Violate any applicable laws or regulations</li>
                    <li>
                      Infringe upon intellectual property rights of others
                    </li>
                    <li>Engage in any activity that could harm minors</li>
                  </ul>
                </li>
                <li>
                  <span className="font-medium">5.3</span> Unauthorized use may
                  result in termination of your account and legal action.
                </li>
                <li>
                  <span className="font-medium">5.4</span> You are responsible
                  for all content you submit and must ensure it does not violate
                  these Terms or applicable laws.
                </li>
              </ul>
            </article>

            {/* 6. Intellectual Property */}
            <article>
              <h2 className="text-xl font-semibold text-eduBlue mb-3">
                6. Intellectual Property
              </h2>
              <ul className="pl-6 space-y-2 text-gray-700 text-sm md:text-base">
                <li>
                  <span className="font-medium">6.1</span> All content on
                  EduPrint, including logos, design, software, study
                  material, tests, and certificates, are the intellectual
                  property of EduCerns Technologies Pvt. Ltd. or its licensors.
                </li>
                <li>
                  <span className="font-medium">6.2</span> You are granted a
                  limited, non-transferable, non-exclusive license to use the
                  Platform for personal and educational purposes only.
                </li>
                <li>
                  <span className="font-medium">6.3</span> You may not
                  reproduce, distribute, modify, or create derivative works from
                  our content without explicit written permission.
                </li>
                <li>
                  <span className="font-medium">6.4</span> Any content you
                  submit grants us a non-exclusive license to use it for
                  Platform operations and improvements.
                </li>
              </ul>
            </article>

            {/* 7. Certification & Examination */}
            <article>
              <h2 className="text-xl font-semibold text-eduBlue mb-3">
                7. Certification & Examination
              </h2>
              <ul className="pl-6 space-y-2 text-gray-700 text-sm md:text-base">
                <li>
                  <span className="font-medium">7.1</span> Issuance of
                  certificates is subject to successful completion of exams and
                  verification of details provided by the user.
                </li>
                <li>
                  <span className="font-medium">7.2</span> Certificates are
                  non-transferable and issued solely to the registered
                  individual.
                </li>
                <li>
                  <span className="font-medium">7.3</span> Any misuse of
                  certificates (including falsification or misrepresentation)
                  may lead to permanent account suspension and legal liability.
                </li>
                <li>
                  <span className="font-medium">7.4</span> We reserve the right
                  to verify the identity of certificate holders and may require
                  additional documentation.
                </li>
                <li>
                  <span className="font-medium">7.5</span> Examination
                  procedures, including proctoring requirements and technical
                  specifications, will be communicated prior to examination.
                </li>
                <li>
                  <span className="font-medium">7.6</span> Certificate validity
                  periods, if applicable, will be clearly stated on each
                  certificate.
                </li>
              </ul>
            </article>

            {/* 8. Payments & Fees */}
            <article>
              <h2 className="text-xl font-semibold text-eduBlue mb-3">
                8. Payments & Fees
              </h2>
              <ul className="pl-6 space-y-2 text-gray-700 text-sm md:text-base">
                <li>
                  <span className="font-medium">8.1</span> By enrolling for
                  certification or related services, you agree to pay the
                  applicable fees displayed on the Platform.
                </li>
                <li>
                  <span className="font-medium">8.2</span> All payments are
                  processed through secure & authorized payment gateways and are
                  subject to their terms and conditions.
                </li>
                <li>
                  <span className="font-medium">8.3</span> Refunds and
                  cancellations are governed by our separate Refund &
                  Cancellation Policy.
                </li>
                <li>
                  <span className="font-medium">8.4</span> EduCerns reserves the
                  right to revise fees with reasonable notice to users.
                </li>
                <li>
                  <span className="font-medium">8.5</span> All fees are
                  inclusive of applicable taxes unless otherwise stated.
                </li>
                <li>
                  <span className="font-medium">8.6</span> Payment failures may
                  result in suspension of services until payment is completed.
                </li>
              </ul>
            </article>

            {/* 9. Data Protection & Privacy */}
            <article>
              <h2 className="text-xl font-semibold text-eduBlue mb-3">
                9. Data Protection & Privacy
              </h2>
              <ul className="pl-6 space-y-2 text-gray-700 text-sm md:text-base">
                <li>
                  <span className="font-medium">9.1</span> Your privacy is
                  important to us. Please review our Privacy Policy to
                  understand how we collect, use, and protect your information.
                </li>
                <li>
                  <span className="font-medium">9.2</span> By using the
                  Platform, you consent to the collection and use of your data
                  as described in our Privacy Policy.
                </li>
                <li>
                  <span className="font-medium">9.3</span> We implement
                  reasonable security measures to protect your data but cannot
                  guarantee absolute security.
                </li>
              </ul>
            </article>

            {/* 10. User Conduct & Community Guidelines */}
            <article>
              <h2 className="text-xl font-semibold text-eduBlue mb-3">
                10. User Conduct & Community Guidelines
              </h2>
              <ul className="pl-6 space-y-2 text-gray-700 text-sm md:text-base">
                <li>
                  <span className="font-medium">10.1</span> Users must maintain
                  respectful and professional conduct on the Platform.
                </li>
                <li>
                  <span className="font-medium">10.2</span> Harassment,
                  discrimination, or abusive behavior towards other users or
                  staff is strictly prohibited.
                </li>
                <li>
                  <span className="font-medium">10.3</span> Users must respect
                  the learning environment and not disrupt others' educational
                  experience.
                </li>
              </ul>
            </article>

            {/* 11. Disclaimer & Limitation of Liability */}
            <article>
              <h2 className="text-xl font-semibold text-eduBlue mb-3">
                11. Disclaimer & Limitation of Liability
              </h2>
              <ul className="pl-6 space-y-2 text-gray-700 text-sm md:text-base">
                <li>
                  <span className="font-medium">11.1</span> EduPrint
                  provides services on an "as is" and "as available" basis,
                  without warranties of any kind, express or implied.
                </li>
                <li>
                  <span className="font-medium">11.2</span> We do not guarantee
                  that using EduPrint will guarantee employment, job
                  placement, or business success.
                </li>
                <li>
                  <span className="font-medium">11.3</span> We disclaim all
                  warranties including merchantability, fitness for a particular
                  purpose, and non-infringement.
                </li>
                <li>
                  <span className="font-medium">11.4</span> EduCerns shall not
                  be liable for any direct, indirect, incidental, special,
                  consequential, or punitive damages arising from your use of
                  the Platform.
                </li>
                <li>
                  <span className="font-medium">11.5</span> Our total liability
                  shall not exceed the amount paid by you for the specific
                  service giving rise to the claim.
                </li>
                <li>
                  <span className="font-medium">11.6</span> These limitations
                  apply even if we have been advised of the possibility of such
                  damages.
                </li>
              </ul>
            </article>

            {/* 12. Third-Party Links & Services */}
            <article>
              <h2 className="text-xl font-semibold text-eduBlue mb-3">
                12. Third-Party Links & Services
              </h2>
              <ul className="pl-6 space-y-2 text-gray-700 text-sm md:text-base">
                <li>
                  <span className="font-medium">12.1</span> EduPrint may
                  contain links to third-party websites or services.
                </li>
                <li>
                  <span className="font-medium">12.2</span> We are not
                  responsible for the content, terms, policies, or practices of
                  third-party services.
                </li>
                <li>
                  <span className="font-medium">12.3</span> Your interactions
                  with third-party services are solely between you and the third
                  party.
                </li>
              </ul>
            </article>

            {/* 13. Termination */}
            <article>
              <h2 className="text-xl font-semibold text-eduBlue mb-3">
                13. Termination
              </h2>
              <ul className="pl-6 space-y-2 text-gray-700 text-sm md:text-base">
                <li>
                  <span className="font-medium">13.1</span> EduCerns may suspend
                  or terminate your access if you:
                  <ul className="list-disc pl-6 mt-2 space-y-1">
                    <li>Violate these Terms</li>
                    <li>Engage in fraudulent or illegal activity</li>
                    <li>Misuse the Platform in any way</li>
                    <li>Fail to pay applicable fees</li>
                  </ul>
                </li>
                <li>
                  <span className="font-medium">13.2</span> You may terminate
                  your account at any time by contacting our support team.
                </li>
                <li>
                  <span className="font-medium">13.3</span> Upon termination,
                  your right to access the Platform will cease immediately.
                </li>
                <li>
                  <span className="font-medium">13.4</span> Sections that by
                  their nature should survive termination will remain in effect.
                </li>
              </ul>
            </article>

            {/* 14. Indemnity */}
            <article>
              <h2 className="text-xl font-semibold text-eduBlue mb-3">
                14. Indemnity
              </h2>
              <p className="text-gray-700 text-sm md:text-base">
                You agree to indemnify and hold harmless EduCerns Technologies
                Pvt. Ltd., its affiliates, directors, employees, and partners
                against any claims, damages, losses, costs, or liabilities
                arising out of your misuse of the Platform, breach of these
                Terms, or violation of any third-party rights.
              </p>
            </article>

            {/* 15. Force Majeure */}
            <article>
              <h2 className="text-xl font-semibold text-eduBlue mb-3">
                15. Force Majeure
              </h2>
              <p className="text-gray-700 text-sm md:text-base">
                EduCerns shall not be liable for delays or failures in
                performance caused by events beyond its reasonable control,
                including but not limited to natural disasters, system failures,
                government actions, pandemics, or other unforeseeable
                circumstances.
              </p>
            </article>

            {/* 16. Dispute Resolution */}
            <article>
              <h2 className="text-xl font-semibold text-eduBlue mb-3">
                16. Dispute Resolution
              </h2>
              <ul className="pl-6 space-y-2 text-gray-700 text-sm md:text-base">
                <li>
                  <span className="font-medium">16.1</span> We encourage users
                  to first contact our support team to resolve any disputes
                  amicably.
                </li>
                <li>
                  <span className="font-medium">16.2</span> If informal
                  resolution is not possible, disputes may be subject to
                  mediation before pursuing legal action.
                </li>
                <li>
                  <span className="font-medium">16.3</span> Any arbitration will
                  be conducted in accordance with the Indian Arbitration and
                  Conciliation Act, 2015.
                </li>
              </ul>
            </article>

            {/* 17. Governing Law & Jurisdiction */}
            <article>
              <h2 className="text-xl font-semibold text-eduBlue mb-3">
                17. Governing Law & Jurisdiction
              </h2>
              <ul className="pl-6 space-y-2 text-gray-700 text-sm md:text-base">
                <li>
                  <span className="font-medium">17.1</span> These Terms are
                  governed by and construed in accordance with the laws of
                  India.
                </li>
                <li>
                  <span className="font-medium">17.2</span> All disputes shall
                  be subject to the exclusive jurisdiction of the courts in
                  Bhiwandi, Maharashtra.
                </li>
                <li>
                  <span className="font-medium">17.3</span> If any provision of
                  these Terms is found unenforceable, the remaining provisions
                  will continue in full force.
                </li>
              </ul>
            </article>

            {/* 18. Miscellaneous */}
            <article>
              <h2 className="text-xl font-semibold text-eduBlue mb-3">
                18. Miscellaneous
              </h2>
              <ul className="pl-6 space-y-2 text-gray-700 text-sm md:text-base">
                <li>
                  <span className="font-medium">18.1</span> These Terms
                  constitute the entire agreement between you and EduCerns
                  regarding the Platform.
                </li>
                <li>
                  <span className="font-medium">18.2</span> No waiver of any
                  term will be deemed a continuing waiver.
                </li>
                <li>
                  <span className="font-medium">18.3</span> Section headings are
                  for convenience only and do not affect interpretation.
                </li>
                <li>
                  <span className="font-medium">18.4</span> We may assign these
                  Terms without notice; you may not assign your rights without
                  our written consent.
                </li>
              </ul>
            </article>

            {/* 19. Accessibility & Technical Support */}
            <article>
              <h2 className="text-xl font-semibold text-eduBlue mb-3">
                19. Accessibility & Technical Support
              </h2>
              <ul className="pl-6 space-y-2 text-gray-700 text-sm md:text-base">
                <li>
                  <span className="font-medium">19.1</span> We strive to make
                  our Platform accessible to users with disabilities.
                </li>
                <li>
                  <span className="font-medium">19.2</span> Technical support is
                  available through the contact methods listed below during
                  business hours.
                </li>
                <li>
                  <span className="font-medium">19.3</span> System requirements
                  and troubleshooting information are available on our website.
                </li>
              </ul>
            </article>

            {/* 20. Contact Us */}
          </section>
          <footer className="mt-10 bg-gray-50 border-t border-gray-200 py-6 px-4 rounded-lg shadow-sm">
            <h2 className="text-lg md:text-xl font-semibold text-eduBlue mb-3">
              Contact Us
            </h2>
            <div className="text-gray-700 text-sm md:text-base space-y-2">
              <p className="font-medium">EduCerns Technologies Pvt. Ltd.</p>
              <p>
                📍 Registered Office: 472, Kasar Ali, Opp. Markandeshwar Mandir,
                Anjur, Bhiwandi, Thane, Maharashtra, India – 421302
              </p>
              <p>📩 Email: support@educerns.org</p>
              <p>📞 Phone: +91-8855856055</p>
            </div>
          </footer>
        </main>
    </div>
  );
};

export default TermsOfService;
